# Generated by Django 3.2.22 on 2023-10-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shared_comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
