# Generated by Django 3.2.22 on 2023-10-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_post_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
